### ISSUE TITLE
bogus URL README.md 

### ISSUE THREAD

**Issue by igouy** [onli/stressTest#1]
wildervanck.eu has nothing to do with the benchmarks game project.

    http://benchmarksgame.wildervanck.eu/fannkuchredux-java-1.html

Here is the URL for the benchmarks game public website — 

    https://benchmarksgame-team.pages.debian.net/benchmarksgame/

**Comment by onli** [comment]
Seems like a mirror to me? But it's definitely the URL I found.

I changed the link in the readme now. Or did you saw it anywhere else?

**Comment by igouy** [comment]
Thanks.

It's at-least 2 years out-of-date.

**Comment by onli** [comment]
Okay. Thanks :)
